// Joystick Definitions
#define ANALOG_AXIS_PIN_X GP28
#define ANALOG_AXIS_PIN_Y GP29

#define JOYSTICK_BUTTON_COUNT 0
#define JOYSTICK_AXIS_COUNT 2
#define JOYSTICK_AXIS_RESOLUTION 10

// Bootmagic
#define BOOTMAGIC_ROW_LEFT 0
#define BOOTMAGIC_COLUMN_LEFT 0

#define VIAL_KEYBOARD_UID {0x34, 0x0F, 0xE7, 0xA5, 0x82, 0x88, 0x24, 0xEC}

#define VIAL_UNLOCK_COMBO_ROWS {2, 2}
#define VIAL_UNLOCK_COMBO_COLS {0, 3}
