// Joystick Definitions
#define ANALOG_AXIS_PIN_X GP28
#define ANALOG_AXIS_PIN_Y GP29

#define JOYSTICK_BUTTON_COUNT 0
#define JOYSTICK_AXIS_COUNT 2
#define JOYSTICK_AXIS_RESOLUTION 10

// Bootmagic
#define BOOTMAGIC_ROW_LEFT 0
#define BOOTMAGIC_COLUMN_LEFT 0

// TODO: Define Status Pin LEDS
